version: "3"

services:

  radius:
    container_name: radius
    build:
      context: .
    restart: unless-stopped
    ports:
      - "${PORT_1}:${PORT_1}/udp"
      - "${PORT_2}:${PORT_2}/udp"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      # Optional settings
      - PORT_1=${PORT_1}
      - PORT_2=${PORT_2}
    volumes:
      - ./data/freeradius:/data
    # If you want to disable debug output, remove the command parameter
    # command: -X 

      